
language: python

python:
    - "2.7"
    - "3.6"
    - "3.7"

before_install:
    # setup miniconda
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    - conda config --set channel_priority strict
    - conda update -q conda
    - conda info -a

install:
    - conda create --name regionmask -c conda-forge python=$TRAVIS_PYTHON_VERSION
    - source activate regionmask
    - conda install -c conda-forge cartopy geopandas xarray pytest pytest-cov codecov
    - python setup.py install
    #- https://stackoverflow.com/a/48728877/3010700
    - "export MPLBACKEND=Agg"

script:
    - py.test --cov=regionmask .

after_success:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
        codecov -t 32cfbc8b-8d1a-4540-8bc3-f6a1a695c554
      fi 
