# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64

name: regionmask-docs
channels:
 - conda-forge
dependencies:
 - _libgcc_mutex=0.1=main
 - affine=2.3.0=py_0
 - alabaster=0.7.12=py_0
 - attrs=19.3.0=py_0
 - babel=2.7.0=py_0
 - backcall=0.1.0=py_0
 - basemap=1.2.1=py37hd759880_1
 - bleach=3.1.0=py_0
 - boost-cpp=1.70.0=h8e57a91_2
 - bzip2=1.0.8=h516909a_2
 - ca-certificates=2019.11.28=hecc5488_0
 - cairo=1.16.0=hfb77d84_1002
 - cartopy=0.17.0=py37hd759880_1006
 - certifi=2019.11.28=py37_0
 - cffi=1.13.2=py37h8022711_0
 - cfitsio=3.470=hb60a0a2_2
 - cftime=1.0.4.2=py37hc1659b7_0
 - chardet=3.0.4=py37_1003
 - click=7.0=py_0
 - click-plugins=1.1.1=py_0
 - cligj=0.5.0=py_0
 - cryptography=2.8=py37h72c5cf5_1
 - curl=7.65.3=hf8cf82a_0
 - cycler=0.10.0=py_2
 - dbus=1.13.6=he372182_0
 - decorator=4.4.1=py_0
 - defusedxml=0.6.0=py_0
 - docutils=0.15.2=py37_0
 - entrypoints=0.3=py37_1000
 - expat=2.2.5=he1b5a44_1004
 - fiona=1.8.6=py37hf242f0b_3
 - fontconfig=2.13.1=h86ecdb6_1001
 - freetype=2.10.0=he983fc9_1
 - freexl=1.0.5=h14c3975_1002
 - gdal=2.4.1=py37h5f563d9_8
 - geopandas=0.6.2=py_0
 - geos=3.7.2=he1b5a44_2
 - geotiff=1.4.3=hb6868eb_1001
 - gettext=0.19.8.1=hc5be6a0_1002
 - giflib=5.1.7=h516909a_1
 - glib=2.58.3=py37h6f030ca_1002
 - gst-plugins-base=1.14.5=h0935bb2_0
 - gstreamer=1.14.5=h36ae1b5_0
 - hdf4=4.2.13=hf30be14_1003
 - hdf5=1.10.5=nompi_h3c11f04_1104
 - icu=64.2=he1b5a44_1
 - idna=2.8=py37_1000
 - imagesize=1.1.0=py_0
 - importlib_metadata=1.3.0=py37_0
 - ipykernel=5.1.3=py37h5ca1d4c_0
 - ipython=7.8.0=py37h5ca1d4c_0
 - ipython_genutils=0.2.0=py_1
 - ipywidgets=7.5.1=py_0
 - jedi=0.15.1=py37_0
 - jinja2=2.10.3=py_0
 - jpeg=9c=h14c3975_1001
 - json-c=0.13.1=h14c3975_1001
 - jsonschema=3.2.0=py37_0
 - jupyter=1.0.0=py_2
 - jupyter_client=5.3.3=py37_1
 - jupyter_console=6.0.0=py_0
 - jupyter_contrib_core=0.3.3=py_2
 - jupyter_contrib_nbextensions=0.5.1=py37_0
 - jupyter_core=4.6.1=py37_0
 - jupyter_highlight_selected_word=0.2.0=py37_1000
 - jupyter_latex_envs=1.4.4=py37_1000
 - jupyter_nbextensions_configurator=0.4.1=py37_0
 - kealib=1.4.10=h58c409b_1005
 - kiwisolver=1.1.0=py37hc9558a2_0
 - krb5=1.16.4=h2fd8d38_0
 - ld_impl_linux-64=2.33.1=h53a641e_7
 - libblas=3.8.0=14_openblas
 - libcblas=3.8.0=14_openblas
 - libclang=9.0.0=default_hde54327_4
 - libcurl=7.65.3=hda55be3_0
 - libdap4=3.20.4=hd3bb157_0
 - libedit=3.1.20170329=hf8c457e_1001
 - libffi=3.2.1=he1b5a44_1006
 - libgcc-ng=9.2.0=hdf63c60_0
 - libgdal=2.4.1=heae24aa_8
 - libgfortran-ng=7.3.0=hdf63c60_2
 - libiconv=1.15=h516909a_1005
 - libkml=1.3.0=h4fcabce_1010
 - liblapack=3.8.0=14_openblas
 - libllvm9=9.0.0=hc9558a2_3
 - libnetcdf=4.6.2=h303dfb8_1003
 - libopenblas=0.3.7=h5ec1e0e_5
 - libpng=1.6.37=hed695b0_0
 - libpq=11.5=hd9ab2ff_1
 - libsodium=1.0.17=h516909a_0
 - libspatialindex=1.9.3=he1b5a44_1
 - libspatialite=4.3.0a=h79dc798_1030
 - libssh2=1.8.2=h22169c7_2
 - libstdcxx-ng=9.2.0=hdf63c60_0
 - libtiff=4.1.0=hc3755c2_1
 - libuuid=2.32.1=h14c3975_1000
 - libxcb=1.13=h14c3975_1002
 - libxkbcommon=0.9.1=hebb1f50_0
 - libxml2=2.9.10=hee79883_0
 - libxslt=1.1.33=h31b3aaa_0
 - lxml=4.4.2=py37h7ec2d77_0
 - lz4-c=1.8.3=he1b5a44_1001
 - markupsafe=1.1.1=py37h516909a_0
 - matplotlib=3.1.2=py37_1
 - matplotlib-base=3.1.2=py37h250f245_1
 - mistune=0.8.4=py37h516909a_1000
 - mock=3.0.5=py37_0
 - more-itertools=8.0.2=py_0
 - munch=2.5.0=py_0
 - nbconvert=5.6.1=py37_0
 - nbformat=4.4.0=py_1
 - ncurses=6.1=hf484d3e_1002
 - netcdf4=1.5.1.2=py37h73a1b54_1
 - notebook=6.0.1=py37_0
 - nspr=4.24=he1b5a44_0
 - nss=3.47=he751ad9_0
 - numpy=1.17.3=py37h95a1406_0
 - numpydoc=0.9.1=py_0
 - olefile=0.46=py_0
 - openjpeg=2.3.1=h981e76c_3
 - openssl=1.1.1d=h516909a_0
 - owslib=0.19.0=py_1
 - packaging=19.2=py_0
 - pandas=0.25.3=py37hb3f55d8_0
 - pandoc=2.9=0
 - pandocfilters=1.4.2=py_1
 - parso=0.5.2=py_0
 - pcre=8.43=he1b5a44_0
 - pexpect=4.7.0=py37_0
 - pickleshare=0.7.5=py37_1000
 - pillow=6.2.1=py37hd70f55b_1
 - pip=19.3.1=py37_0
 - pixman=0.38.0=h516909a_1003
 - poppler=0.67.0=h14e79db_8
 - poppler-data=0.4.9=1
 - postgresql=11.5=hc63931a_1
 - proj4=5.2.0=he1b5a44_1006
 - prometheus_client=0.7.1=py_0
 - prompt_toolkit=2.0.10=py_0
 - pthread-stubs=0.4=h14c3975_1001
 - ptyprocess=0.6.0=py_1001
 - pycparser=2.19=py37_1
 - pyepsg=0.4.0=py_0
 - pygments=2.5.2=py_0
 - pykdtree=1.3.1=py37hc1659b7_1002
 - pyopenssl=19.1.0=py37_0
 - pyparsing=2.4.5=py_0
 - pyproj=1.9.6=py37h516909a_1002
 - pyqt=5.12.3=py37hcca6a23_1
 - pyqt5-sip=4.19.18=pypi_0
 - pyqtwebengine=5.12.1=pypi_0
 - pyrsistent=0.15.6=py37h516909a_0
 - pyshp=2.1.0=py_0
 - pysocks=1.7.1=py37_0
 - python=3.7.3=h357f687_2
 - python-dateutil=2.8.1=py_0
 - pytz=2019.3=py_0
 - pyyaml=5.2=py37h516909a_0
 - pyzmq=18.1.1=py37h1768529_0
 - qt=5.12.5=hd8c4c69_1
 - qtconsole=4.6.0=py_0
 - rasterio=1.0.25=py37hdff7cfa_0
 - readline=8.0=hf8c457e_0
 - regionmask=0.4.0+dev=dev_0
 - requests=2.22.0=py37_1
 - rtree=0.9.3=py37h7b0cdae_0
 - scipy=1.3.2=py37h921218d_0
 - send2trash=1.5.0=py_0
 - setuptools=42.0.2=py37_0
 - shapely=1.6.4=py37hec07ddf_1006
 - six=1.13.0=py37_0
 - snowballstemmer=2.0.0=py_0
 - snuggs=1.4.7=py_0
 - sphinx=2.2.2=py_0
 - sphinx_rtd_theme=0.4.3=py_0
 - sphinxcontrib-applehelp=1.0.1=py_0
 - sphinxcontrib-devhelp=1.0.1=py_0
 - sphinxcontrib-htmlhelp=1.0.2=py_0
 - sphinxcontrib-jsmath=1.0.1=py_0
 - sphinxcontrib-qthelp=1.0.2=py_0
 - sphinxcontrib-serializinghtml=1.1.3=py_0
 - sqlite=3.30.1=hcee41ef_0
 - terminado=0.8.3=py37_0
 - testpath=0.4.4=py_0
 - tk=8.6.10=hed695b0_0
 - tornado=6.0.3=py37h516909a_0
 - traitlets=4.3.3=py37_0
 - tzcode=2019a=h516909a_1002
 - urllib3=1.25.7=py37_0
 - wcwidth=0.1.7=py_1
 - webencodings=0.5.1=py_1
 - wheel=0.33.6=py37_0
 - widgetsnbextension=3.5.1=py37_0
 - xarray=0.14.1=py_0
 - xerces-c=3.2.2=h8412b87_1004
 - xorg-kbproto=1.0.7=h14c3975_1002
 - xorg-libice=1.0.10=h516909a_0
 - xorg-libsm=1.2.3=h84519dc_1000
 - xorg-libx11=1.6.9=h516909a_0
 - xorg-libxau=1.0.9=h14c3975_0
 - xorg-libxdmcp=1.1.3=h516909a_0
 - xorg-libxext=1.3.4=h516909a_0
 - xorg-libxrender=0.9.10=h516909a_1002
 - xorg-renderproto=0.11.1=h14c3975_1002
 - xorg-xextproto=7.3.0=h14c3975_1002
 - xorg-xproto=7.0.31=h14c3975_1007
 - xz=5.2.4=h14c3975_1001
 - yaml=0.2.2=h516909a_1
 - zeromq=4.3.2=he1b5a44_2
 - zipp=0.6.0=py_0
 - zlib=1.2.11=h516909a_1006
 - zstd=1.4.4=h3b9ef0a_1
