# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-main.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2019.11.28-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.33.1-h53a641e_7.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-ng-7.3.0-hdf63c60_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-9.2.0-hdf63c60_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandoc-2.9-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/poppler-data-0.4.9-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-9.2.0-hdf63c60_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h516909a_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/expat-2.2.5-he1b5a44_1004.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freexl-1.0.5-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/geos-3.7.2-he1b5a44_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/giflib-5.1.7-h516909a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-64.2-he1b5a44_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9c-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/json-c-0.13.1-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-he1b5a44_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.15-h516909a_1005.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libllvm9-9.0.0-hc9558a2_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libopenblas-0.3.7-h5ec1e0e_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libsodium-1.0.17-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libspatialindex-1.9.3-he1b5a44_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.32.1-h14c3975_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxkbcommon-0.9.1-hebb1f50_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lz4-c-1.8.3-he1b5a44_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.1-hf484d3e_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nspr-4.24-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1d-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pcre-8.43-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pixman-0.38.0-h516909a_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/proj4-5.2.0-he1b5a44_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pthread-stubs-0.4-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tzcode-2019a-h516909a_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-kbproto-1.0.7-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libice-1.0.10-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxau-1.0.9-h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxdmcp-1.1.3-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-renderproto-0.11.1-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xextproto-7.3.0-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xproto-7.0.31-h14c3975_1007.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.4-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yaml-0.2.2-h516909a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/boost-cpp-1.70.0-h8e57a91_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gettext-0.19.8.1-hc5be6a0_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf4-4.2.13-hf30be14_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf5-1.10.5-nompi_h3c11f04_1104.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libblas-3.8.0-14_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libclang-9.0.0-default_hde54327_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libedit-3.1.20170329-hf8c457e_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpng-1.6.37-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libssh2-1.8.2-h22169c7_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxcb-1.13-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.10-hee79883_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-8.0-hf8c457e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.10-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xerces-c-3.2.2-h8412b87_1004.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libsm-1.2.3-h84519dc_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zeromq-4.3.2-he1b5a44_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zstd-1.4.4-h3b9ef0a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freetype-2.10.0-he983fc9_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/kealib-1.4.10-h58c409b_1005.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/krb5-1.16.4-h2fd8d38_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcblas-3.8.0-14_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libkml-1.3.0-h4fcabce_1010.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/liblapack-3.8.0-14_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtiff-4.1.0-hc3755c2_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxslt-1.1.33-h31b3aaa_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.30.1-hcee41ef_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libx11-1.6.9-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.13.1-h86ecdb6_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/geotiff-1.4.3-hb6868eb_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcurl-7.65.3-hda55be3_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpq-11.5-hd9ab2ff_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libspatialite-4.3.0a-h79dc798_1030.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nss-3.47-he751ad9_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openjpeg-2.3.1-h981e76c_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.7.3-h357f687_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxext-1.3.4-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxrender-0.9.10-h516909a_1002.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/affine-2.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/alabaster-0.7.12-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/attrs-19.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backcall-0.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2019.11.28-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cfitsio-3.470-hb60a0a2_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.4-py37_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/curl-7.65.3-hf8cf82a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-4.4.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/defusedxml-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/docutils-0.15.2-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/entrypoints-0.3-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/glib-2.58.3-py37h6f030ca_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/idna-2.8-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/imagesize-1.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipython_genutils-0.2.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/kiwisolver-1.1.0-py37hc9558a2_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lxml-4.4.2-py37h7ec2d77_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/markupsafe-1.1.1-py37h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mistune-0.8.4-py37h516909a_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/more-itertools-8.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numpy-1.17.3-py37h95a1406_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pandocfilters-1.4.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/parso-0.5.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pickleshare-0.7.5-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/postgresql-11.5-hc63931a_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prometheus_client-0.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ptyprocess-0.6.0-py_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pycparser-2.19-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.4.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyshp-2.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.7.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2019.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-5.2-py37h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyzmq-18.1.1-py37h1768529_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/rtree-0.9.3-py37h7b0cdae_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/send2trash-1.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/six-1.13.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/snowballstemmer-2.0.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinx_rtd_theme-0.4.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-applehelp-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-devhelp-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-htmlhelp-1.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-jsmath-1.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-qthelp-1.0.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinxcontrib-serializinghtml-1.1.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/testpath-0.4.4-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tornado-6.0.3-py37h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.1.7-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/webencodings-0.5.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/babel-2.7.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cairo-1.16.0-hfb77d84_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cffi-1.13.2-py37h8022711_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cftime-1.0.4.2-py37hc1659b7_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-plugins-1.1.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cligj-0.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/dbus-1.13.6-he372182_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gstreamer-1.14.5-h36ae1b5_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jedi-0.15.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libdap4-3.20.4-hd3bb157_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libnetcdf-4.6.2-h303dfb8_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mock-3.0.5-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/packaging-19.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pexpect-4.7.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pillow-6.2.1-py37hd70f55b_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pykdtree-1.3.1-py37hc1659b7_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyproj-1.9.6-py37h516909a_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyrsistent-0.15.6-py37h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scipy-1.3.2-py37h921218d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-42.0.2-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/shapely-1.6.4-py37hec07ddf_1006.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/snuggs-1.4.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/terminado-0.8.3-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/traitlets-4.3.3-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/zipp-0.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/bleach-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-2.8-py37h72c5cf5_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gst-plugins-base-1.14.5-h0935bb2_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/importlib_metadata-1.3.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.10.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jupyter_core-4.6.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-base-3.1.2-py37h250f245_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/munch-2.5.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/netcdf4-1.5.1.2-py37h73a1b54_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandas-0.25.3-py37hb3f55d8_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/poppler-0.67.0-h14e79db_8.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pygments-2.5.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/wheel-0.33.6-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/basemap-1.2.1-py37hd759880_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jsonschema-3.2.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jupyter_client-5.3.3-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgdal-2.4.1-heae24aa_8.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pip-19.3.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/prompt_toolkit-2.0.10-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyopenssl-19.1.0-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/qt-5.12.5-hd8c4c69_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/xarray-0.14.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gdal-2.4.1-py37h5f563d9_8.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipython-7.8.0-py37h5ca1d4c_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbformat-4.4.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyqt-5.12.3-py37hcca6a23_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/rasterio-1.0.25-py37hdff7cfa_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/urllib3-1.25.7-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fiona-1.8.6-py37hf242f0b_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipykernel-5.1.3-py37h5ca1d4c_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-3.1.2-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nbconvert-5.6.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/requests-2.22.0-py37_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/geopandas-0.6.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_console-6.0.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/notebook-6.0.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/owslib-0.19.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyepsg-0.4.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/qtconsole-4.6.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/sphinx-2.2.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cartopy-0.17.0-py37hd759880_1006.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter_contrib_core-0.3.3-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/numpydoc-0.9.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/widgetsnbextension-3.5.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipywidgets-7.5.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jupyter_highlight_selected_word-0.2.0-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jupyter_latex_envs-1.4.4-py37_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jupyter_nbextensions_configurator-0.4.1-py37_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyter-1.0.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jupyter_contrib_nbextensions-0.5.1-py37_0.tar.bz2
