name: regionmask-docs

channels:
 - conda-forge

dependencies:
  - python=3.7
  - cartopy=0.17.0
  - intake==0.6.1
  - fsspec==0.8.7
  - pip
  - pip:
    - matplotlib==3.2.1
    - mock
    - sphinx==2.1.2
    - sphinx_rtd_theme==0.4.3
    - pillow
    - rasterio
    - numpy
    - cftime
    - netcdf4
    - geopandas
    - intake_geopandas>=0.2.4
    - aiohttp
    - requests
    - msgpack
    - xarray==0.15.1
    - numpydoc
    - nbconvert
    - jupyter
    - ipython
    - pooch
